function(input, output, session) {
    # Serve outputs -----------------------
    # Reactive UI elements
    output$img_select <- renderUI({
        selectInput("img_id", "Image:", choices=stringr::str_sub(kIMG_FNS, end=-5))
    })

    # Clinical Outputs
    ## Radiograph
    output$radiographImage <- renderImage({
        filename <- stringr::str_interp("${kIMG_DIR}/${input$img_id}.jpg")
        return(list(src = filename, filetype="image/jpeg", alt="Radiograph"))
    }, deleteFile = FALSE)

    # Brush Coordinates
    output$coordinatesTable <- renderTable({bboxCoordinates()})

    # Downloads
    download_usr_input_csvs <- function(ann_type, usr_input_dir = kDIR_USR_INPT) {
        .f_load <- purrr::partial(load_csv_annotation, kANN_DIR=usr_input_dir)
        handle_annotation_download(ann_type, f_load=.f_load)
    }
    output$downloadClassification <- download_usr_input_csvs(ann_type = "classification")
    #output$downloadClassification <- handle_annotation_download("classification", )
    output$downloadSegmentation <- download_usr_input_csvs(ann_type = "segmentation")
    output$downloadClinicalNote <- download_usr_input_csvs(ann_type = "clinical_note")

    # Reactive Conductors -----------------
    ids <- reactive({
        x <- map(kID_FIELDS, function(x) x=input[[x]])
        x$timestamp <- Sys.time()
        x %<>% as.data.frame() %>% purrr::set_names(c("Radiologist Name", "Image ID", "Timestamp"))
    })

    bboxCoordinates <- reactive({
        data.frame(input$bbox_brush[c("xmin", "xmax", "ymin", "ymax")]) %||% data.frame()
    })

    classificationDF <- reactive({
        df <- ids()
        df$Pathologies <- toString(input$pathologies)
        df
    })

    segmentationDF <- reactive({
        df <- ids()
        coords <- bboxCoordinates()
        bind_cols(df, coords)
    })

    clinical_noteDF <- reactive({
        df <- ids()
        df$ClinicalNote <- input$note
        df
    })


    # Reactive Observers -------------------------------------------------------
    # I/O buttons
    observeEvent(input$submit_classification,
                 save_annotation(classificationDF(), "classification"))

    save_segmentation <- function(path) {
        stopifnot(path %in% kDXS_CHR)
        df <- segmentationDF() %>%
            tibble::add_column(Pathology=path)
        save_annotation(df, "segmentation")
    }
    observeEvent(input$submit_cardiomegaly, save_segmentation("cardiomegaly"))
    observeEvent(input$submit_emphysema, save_segmentation("emphysema"))
    observeEvent(input$submit_effusion, save_segmentation("effusion"))

    observeEvent(input$submit_note,
                 save_annotation(clinical_noteDF(), "clinical_note"))

    # Conditionally hide/disable segmentation submission
    observe(shinyjs::toggle("segmentation", anim=TRUE, condition=!is.null(input$pathologies)))
    observe(shinyjs::toggleState("submit_cardiomegaly",
                                 condition = nrow(bboxCoordinates()) > 0 && "cardiomegaly" %in% input$pathologies))
    observe(shinyjs::toggleState("submit_emphysema",
                                 condition = nrow(bboxCoordinates()) > 0 && "emphysema" %in% input$pathologies))
    observe(shinyjs::toggleState("submit_effusion",
                                 condition = nrow(bboxCoordinates()) > 0 && "effusion" %in% input$pathologies))


    # Image/Annotation Sources ---------
    output$imgFp <- renderPrint(kIMG_DIR %>% cat())
    output$annFp <- renderPrint(kDIR_USR_INPT %>% cat())


    # Trace -----------------------------
    # Supplementary Info panel for diagnostics
    shinyjs::onclick("toggleAdvanced",
                     shinyjs::toggle("advanced", anim=TRUE))

    # DIAGNOSTIC SERVER CODE GENERATED BY `cg.R`

    # Reactive Inputs
    output$img_idPrint <- renderPrint(input$img_id %>% str())
    output$user_namePrint <- renderPrint(input$user_name %>% str())
    output$pathologiesPrint <- renderPrint(input$pathologies %>% str())
    output$notePrint <- renderPrint(input$note %>% str())

    # Reactive Conductors
    output$idsPrint <- renderPrint(ids() %>% str())
    output$bboxCoordinatesPrint <- renderPrint(bboxCoordinates() %>% str())
    output$classificationDFPrint <- renderPrint(classificationDF() %>% str())
    output$segmentationDFPrint <- renderPrint(segmentationDF() %>% str())
    output$clinical_noteDFPrint <- renderPrint(clinical_noteDF() %>% str())
}
