function(input, output, session) {
    # Serve outputs -----------------------
    # Reactive UI elements
    output$img_select <- renderUI({
        selectInput("img_id", "Image:", choices=str_sub(img_fns, end=-5))
    })

    # Clinical Outputs
    ## Radiograph
    output$radiographImage <- renderImage({
        filename <- stringr::str_interp("${img_dir}/${input$img_id}.jpg")
        return(list(src = filename, filetype="image/jpeg", alt="Radiograph"))
    }, deleteFile = FALSE)

    # Brush Coordinates
    output$coordinatesTable <- renderTable({bboxCoordinates()})

    # Downloads
    output$downloadClassification <- handle_annotation_download("Classification")
    output$downloadSegmentation <- handle_annotation_download("Segmentation")
    output$downloadClinicalNote <- handle_annotation_download("ClinicalNote")

    # Reactive Conductors -----------------
    ids <- reactive({
        x <- map(id_fields, function(x) x=input[[x]])
        x$timestamp <- Sys.time()
        x %<>% as.data.frame() %>% purrr::set_names(c("Radiologist Name", "Image ID", "Timestamp"))
    })

    bboxCoordinates <- reactive({
        data.frame(input$bbox_brush[c("xmin", "xmax", "ymin", "ymax")]) %||% data.frame()
    })

    classificationDF <- reactive({
        df <- ids()
        df$Pathologies <- toString(input$pathologies)
        df
    })

    segmentationDF <- reactive({
        df <- ids()
        coords <- bboxCoordinates()
        bind_cols(df, coords)
    })

    clinicalNoteDF <- reactive({
        df <- ids()
        df$ClinicalNote <- input$note
        df
    })


    # Reactive Observers -------------------------------------------------------
    # I/O buttons
    observeEvent(input$submit_classification,
                 save_annotation(classificationDF(), "Classification"))

    save_segmentation <- function(path) {
        stopifnot(path %in% indications)
        df <- segmentationDF() %>%
            add_column(Pathology=path)
        save_annotation(df, "Segmentation")
    }
    observeEvent(input$submit_cardiomegaly, save_segmentation("cardiomegaly"))
    observeEvent(input$submit_emphysema, save_segmentation("emphysema"))
    observeEvent(input$submit_effusion, save_segmentation("effusion"))

    observeEvent(input$submit_note,
                 save_annotation(clinicalNoteDF(), "ClinicalNote"))

    # Conditionally hide/disable segmentation submission
    observe(shinyjs::toggle("segmentation", anim=TRUE, condition=!is.null(input$pathologies)))
    observe(shinyjs::toggleState("submit_cardiomegaly",
                                 condition = nrow(bboxCoordinates()) > 0 && "cardiomegaly" %in% input$pathologies))
    observe(shinyjs::toggleState("submit_emphysema",
                                 condition = nrow(bboxCoordinates()) > 0 && "emphysema" %in% input$pathologies))
    observe(shinyjs::toggleState("submit_effusion",
                                 condition = nrow(bboxCoordinates()) > 0 && "effusion" %in% input$pathologies))


    # Image/Annotation Sources ---------
    output$imgFp <- renderPrint(img_dir %>% cat())
    output$annFp <- renderPrint(ann_dir %>% cat())


    # Trace -----------------------------
    # Supplementary Info panel for diagnostics
    shinyjs::onclick("toggleAdvanced",
                     shinyjs::toggle("advanced", anim=TRUE))

    # DIAGNOSTIC SERVER CODE GENERATED BY `cg.R`

    # Reactive Inputs
    output$img_idPrint <- renderPrint(input$img_id %>% str())
    output$user_namePrint <- renderPrint(input$user_name %>% str())
    output$pathologiesPrint <- renderPrint(input$pathologies %>% str())
    output$notePrint <- renderPrint(input$note %>% str())

    # Reactive Conductors
    output$idsPrint <- renderPrint(ids() %>% str())
    output$bboxCoordinatesPrint <- renderPrint(bboxCoordinates() %>% str())
    output$classificationDFPrint <- renderPrint(classificationDF() %>% str())
    output$segmentationDFPrint <- renderPrint(segmentationDF() %>% str())
    output$clinicalNoteDFPrint <- renderPrint(clinicalNoteDF() %>% str())
}
