fluidPage(
    shinyjs::useShinyjs(),
    theme = shinythemes::shinytheme("darkly"),
    div(id="title", align="center",
        titlePanel("CANDI Institutional Radiograph Annotation Dashboard", windowTitle="CANDI RAD")),

    sidebarLayout(
        sidebarPanel(
            textInput("user_name", "Radiologist Name:", value = "Marcus"),
            uiOutput("img_select"),   # Drop-down menu of all images files avail
            hr(),

            p("Data Locations:"),
            p("Image stored on institutional server"),
            verbatimTextOutput("imgFp"),
            p("Annotations stored on institutional server"),
            verbatimTextOutput("annFp"),  # Superfluous rendering to match appearance w/ previous verbatimTextOutput
            hr(),

            p("Downloads:"),
            div(align="center",
                downloadButton("downloadClassification", label="Classification Annotations"),
                downloadButton("downloadSegmentation", label="Segmentation Annotations"),
                downloadButton("downloadClinicalNote", label="Clinical Impression Notes")
            )
        ),

        mainPanel(
            div(id="image", align="center",
                imageOutput("radiographImage", width = 299, height=299,
                        brush = brushOpts(id = "bbox_brush", resetOnNew = TRUE))
            ),
            hr(),

            # Classification ----------
            p(strong("What pathologies are present in the image?")),
            fluidRow(
                column(width = 8,
                       checkboxGroupInput("pathologies", label=NULL, choices=indications)
                ),
                column(width = 4,
                       shiny::tags$br(),
                       actionButton("submit_classification", "Submit Classifications"))
            ),

            # Segmentation -------------
            div(id="segmentation",
                p(strong("Draw a box around the evidence for each identified pathology (submit 1 box per pathology).")),
                fluidRow(
                    div(id="seg_in_panel", align="center",
                        column(width = 5,
                               fluidRow(actionButton("submit_cardiomegaly", "Submit Cardiomegaly Segmentation")),
                               fluidRow(actionButton("submit_emphysema", "Submit Emphysema Segmentation")),
                               fluidRow(actionButton("submit_effusion", "Submit Effusion Segmentation"))
                        ),
                        column(width = 4, shiny::tags$br(), tableOutput("coordinatesTable"))
            ))),

            # Note --------------------
            p(strong("Note Impression:")),
            textAreaInput("note", NULL, "Clinical Impression", width="650px", resize = "both"),
            actionButton("submit_note", "Submit Impression")
    )),
    hr(),

    # Trace ----------------------------
    a(id="toggleAdvanced", "Show/hide Advanced Information"),
    shinyjs::hidden(
        div(id="advanced",
            wellPanel(
                # DIAGNOSTIC UI CODE GENERATED BY `cg.R`

                h2('Inputs'),
                shiny::tags$strong('img_id'), verbatimTextOutput('img_idPrint'),
                shiny::tags$strong('user_name'), verbatimTextOutput('user_namePrint'),
                shiny::tags$strong('pathologies'), verbatimTextOutput('pathologiesPrint'),
                shiny::tags$strong('note'), verbatimTextOutput('notePrint'),

                h2('Conductors'),
                shiny::tags$strong('ids'), verbatimTextOutput('idsPrint'),
                shiny::tags$strong('bboxCoordinates'), verbatimTextOutput('bboxCoordinatesPrint'),
                shiny::tags$strong('classificationDF'), verbatimTextOutput('classificationDFPrint'),
                shiny::tags$strong('segmentationDF'), verbatimTextOutput('segmentationDFPrint'),
                shiny::tags$strong('clinicalNoteDF'), verbatimTextOutput('clinicalNoteDFPrint')
))))
