function(input, output, session) {
    # Image Upload and Display -------------------------------------------------
    filesInDf <- reactive({
        df <- input$filesInputDf %||% data.frame()
    })

    # Predicate reactive expression for gating UI controls
    output$is_uploaded <- reactive({
        !is_empty(filesInDf())
    })
    outputOptions(output, "is_uploaded", suspendWhenHidden = FALSE)

    img_id2fp_chr <- reactive({
        df <- filesInDf()
        if (is_empty(df)) {return(character(0))}
        # 'deframe' user uploaded file df into LUT
        img_id2fp_lut <- df$datapath %>% set_names(df$name)
        names(img_id2fp_lut) %<>% str_sub(end = -5)  # Remove .jpg extension
        img_id2fp_lut
    })

    # Render UI drop-down to select which uploaded file to display
    output$img_select <- renderUI({
        if (is_empty(filesInDf())) {return(NA_character_)}
        selectInput("img_id", "Image:", choices = names(img_id2fp_chr()))
    })

    # Radiograph
    output$radiographImage <- renderImage({
        if (is_empty(img_id2fp_chr())) {return(NULL)}
        fp <- img_id2fp_chr()[input$img_id]
        return(list(src = fp, filetype = "image/jpeg", alt = "Please upload radiograph(s)"))
    }, deleteFile = FALSE)

    # Other outputs ------------------------------------------------------------
    # Brush coordinates
    output$coordinatesTable <- renderTable({bboxCoordinates()})

    # Downloads
    output$downloadClassification <- handle_annotation_download("Classification")
    output$downloadSegmentation <- handle_annotation_download("Segmentation")
    output$downloadClinicalNote <- handle_annotation_download("ClinicalNote")

    # Image/Annotation sources
    output$imgTmpFp <- renderPrint({
        if (is_empty(filesInDf())) {return(NA_character_)}
        pth <- filesInDf() %>% filter(str_sub(name, end = -5) == input$img_id) %$% datapath
        cat(pth)
    })
    output$annotationURL <- renderPrint(cat(gsURL))

    # Reactive Conductors -----------------
    ids <- reactive({
        if (is_empty(filesInDf())) {return(NULL)}
        x <- map(id_fields, function(x) x = input[[x]])
        x$timestamp <- Sys.time()
        x %<>% as.df %>% set_names(c("Radiologist Name", "Image ID", "Timestamp"))
        x
    })

    bboxCoordinates <- reactive({
        data.frame(input$bbox_brush[c("xmin", "xmax", "ymin", "ymax")]) %||% data.frame()
    })

    classificationDF <- reactive({
        df <- ids()
        df$Pathologies <- toString(input$pathologies)
        df
    })

    segmentationDF <- reactive({
        df <- ids()
        coords <- bboxCoordinates()
        bind_cols(df, coords)
    })

    clinicalNoteDF <- reactive({
        df <- ids()
        df$ClinicalNote <- input$note
        df
    })


    # Reactive Observers -------------------------------------------------------
    # I/O buttons
    observeEvent(input$submit_classification,
        save_annotation(classificationDF(), "Classification"))

    save_segmentation <- function(path) {
        stopifnot(path %in% indications)
        df <- segmentationDF() %>%
            add_column(Pathology=path)
        save_annotation(df, "Segmentation")
    }
    observeEvent(input$submit_cardiomegaly, save_segmentation("cardiomegaly"))
    observeEvent(input$submit_emphysema, save_segmentation("emphysema"))
    observeEvent(input$submit_effusion, save_segmentation("effusion"))

    observeEvent(input$submit_note,
                 save_annotation(clinicalNoteDF(), "ClinicalNote"))

    # Conditionally hide/disable segmentation submission
    observe(shinyjs::toggle("segmentation", anim=TRUE, condition=!is.null(input$pathologies)))
    observe(shinyjs::toggleState("submit_cardiomegaly",
                                 condition = nrow(bboxCoordinates()) > 0 && "cardiomegaly" %in% input$pathologies))
    observe(shinyjs::toggleState("submit_emphysema",
                                 condition = nrow(bboxCoordinates()) > 0 && "emphysema" %in% input$pathologies))
    observe(shinyjs::toggleState("submit_effusion",
                                 condition = nrow(bboxCoordinates()) > 0 && "effusion" %in% input$pathologies))


    # Supplementary Info panel for diagnostics
    shinyjs::onclick("toggleAdvanced",
                     shinyjs::toggle("advanced"))

    # Trace --------------------------------------------------------------------
    # DIAGNOSTIC SERVER CODE GENERATED BY `cg.R`

    # Reactive Inputs
    output$img_idPrint <- renderPrint(input$img_id %>% str())
    output$user_namePrint <- renderPrint(input$user_name %>% str())
    output$filesInputDfPrint <- renderPrint(input$filesInputDf %>% str())
    output$pathologiesPrint <- renderPrint(input$pathologies %>% str())

    # Reactive Conductors
    output$filesInDfPrint <- renderPrint(filesInDf() %>% str())
    output$img_id2fp_chrPrint <- renderPrint(img_id2fp_chr() %>% str())
    output$idsPrint <- renderPrint(ids() %>% str())
    output$bboxCoordinatesPrint <- renderPrint(bboxCoordinates() %>% str())
    output$classificationDFPrint <- renderPrint(classificationDF() %>% str())
    output$segmentationDFPrint <- renderPrint(segmentationDF() %>% str())
}
