function(input, output, session) {
    # Serve outputs -----------------------
    # Reactive UI elements
    output$img_select <- renderUI({
        selectInput("img_id", "Image:", choices=str_sub(img_fns, end=-5))
    })

    # Radiograph
    output$radiographImage <- renderImage({
        filename <- stringr::str_interp("www/${input$img_id}.jpg")
        return(list(src = filename, filetype="image/jpeg", alt="Radiograph"))
    }, deleteFile = FALSE)

    # Brush Coordinates
    output$coordinatesTable <- renderTable({bboxCoordinates()})

    # Downloads
    output$downloadClassification <- downloadHandler(
        filename = function() {"classification_annotations.csv"},
        content = function(file) {write.csv(load_classifications(), file, row.names=FALSE)},
        contentType = "text/csv"
    )
    output$downloadSegmentation <- downloadHandler(
        filename = "segmentation_annotations.csv",
        content = function(file) {write.csv(load_segmentations(), file, row.names=FALSE)},
        contentType = "text/csv"
    )

    # Reactive Conductors -----------------
    ids <- reactive({
        x <- map(id_fields, function(x) x=input[[x]])
        x$timestamp <- Sys.time()
        x %<>% as.data.frame() %>% set_names(c("Radiologist Name", "Image ID", "Timestamp"))
    })

    bboxCoordinates <- reactive({
        data.frame(input$bbox_brush[c("xmin", "xmax", "ymin", "ymax")]) %||% data.frame()
    })

    classificationDF <- reactive({
        df <- ids()
        df$Pathologies <- toString(input$pathologies)
        df
    })

    segmentationDF <- reactive({
        df <- ids()
        coords <- bboxCoordinates()
        bind_cols(df, coords)
    })


    # Reactive Observers -------------------------------------------------------
    observeEvent(input$submit_classification,
                 {save_classification(classificationDF())}
                 )

    observeEvent(input$submit_cardiomegaly,
                 {
                     df <- segmentationDF() %>%
                         add_column(Pathology="Cardiomegaly")
                     save_segmentation(df)
                 })

    observeEvent(input$submit_emphysema,
                 {
                     df <- segmentationDF() %>%
                         add_column(Pathology="Emphysema")
                     save_segmentation(df)
                 })

    observeEvent(input$submit_effusion,
                 {
                     df <- segmentationDF() %>%
                         add_column(Pathology="Pleural Effusion")
                     save_segmentation(df)
                 })

    observe(
        shinyjs::toggle("segmentation", anim=TRUE, condition=!is.null(input$pathologies))
    )
    observe(
        shinyjs::toggleState("submit_cardiomegaly",
                             condition = nrow(bboxCoordinates()) > 0 && "cardiomegaly" %in% input$pathologies)
    )
    observe(
        shinyjs::toggleState("submit_emphysema",
                             condition = nrow(bboxCoordinates()) > 0 && "emphysema" %in% input$pathologies)
    )
    observe(
        shinyjs::toggleState("submit_effusion",
                             condition = nrow(bboxCoordinates()) > 0 && "effusion" %in% input$pathologies)
    )


    # FSIO ---------
    output$imgFp <- renderPrint(img_dir %>% cat())
    output$annFp <- renderPrint(ann_dir %>% cat())



    # Supplementary Info panel for diagnostics
    shinyjs::onclick("toggleAdvanced",
                     shinyjs::toggle("advanced"))
    # DIAGNOSTIC SERVER CODE GENERATED BY `cg.R`

    # Reactive Inputs
    output$img_idPrint <- renderPrint(input$img_id %>% str())
    output$radiologistPrint <- renderPrint(input$radiologist %>% str())
    output$pathologiesPrint <- renderPrint(input$pathologies %>% str())

    # Reactive Conductors
    output$idsPrint <- renderPrint(ids() %>% str())
    output$bboxCoordinatesPrint <- renderPrint(bboxCoordinates() %>% str())
    output$classificationDFPrint <- renderPrint(classificationDF() %>% str())
    output$segmentationDFPrint <- renderPrint(segmentationDF() %>% str())
}
