fluidPage(
    shinyjs::useShinyjs(),
    theme = shinytheme("darkly"),
    titlePanel("Institutional Radiology Study Annotator", windowTitle="Institional RSAnnotator"),
    sidebarLayout(
    	sidebarPanel(
    	    textInput("radiologist", "Radiologist Name:", value = "Marcus"),
    	    uiOutput("img_select"),   # Drop-down menu of all images files avail
    	    hr(),
    	    downloadButton("downloadClassification", label="Download Classification Annotations"),
    	    downloadButton("downloadSegmentation", label="Download Segmentation Annotations"),
    	    hr(),
    	    p("Image stored locally:"),
    	    verbatimTextOutput("imgFp"),
    	    p("Annotations stored locally:"),
    	    verbatimTextOutput("annFp")  # Superfluous rendering to match appearance w/ previous verbatimTextOutput
        ),

        mainPanel(
    	    # Display Radiograph ---------------
    	    fluidRow(
    	        column(4, offset=3,
        		    imageOutput("radiographImage", width = 299, height=299,
        			        brush = brushOpts(id = "bbox_brush", resetOnNew = TRUE),
        		    )
        		)
    	    ),
    	    hr(),

    	    # Classification ----------
    	    p(strong("What pathologies are present in the image?")),
    	    fluidRow(
    	        column(width = 5, offset=1,
    		       checkboxGroupInput("pathologies", label=NULL, choices=indications)
    	        ),
    	        column(width = 4,
    		       actionButton("submit_classification", "Submit Classifications")
    		    )
    	   ),

    	   div(id="segmentation",
        	   # Segmentation -------------
        	   p(strong("Draw a box around the evidence for each identified pathology (submit 1 box per pathology).")),
        	   fluidRow(
        	       column(width = 5, offset=1,
        	               fluidRow(actionButton("submit_cardiomegaly", "Submit Cardiomegaly Segmentation")),
        	               fluidRow(actionButton("submit_emphysema", "Submit Emphysema Segmentation")),
        	               fluidRow(actionButton("submit_effusion", "Submit Effusion Segmentation"))
        	       ),
        	       column(width = 4,
        	               tableOutput("coordinatesTable")
        	       )
        	   )
    	   )
    	)
    ),  # end sidebarLayout

    hr(),

    a(id="toggleAdvanced", "Show/hide Advanced Information"),
    shinyjs::hidden(
        div(id="advanced",
            wellPanel(
                # DIAGNOSTIC UI CODE GENERATED BY `cg.R`
                h2('Inputs'),
                tags$strong('img_id'), verbatimTextOutput('img_idPrint'),
                tags$strong('radiologist'), verbatimTextOutput('radiologistPrint'),
                tags$strong('pathologies'), verbatimTextOutput('pathologiesPrint'),

                h2('Conductors'),
                tags$strong('ids'), verbatimTextOutput('idsPrint'),
                tags$strong('bboxCoordinates'), verbatimTextOutput('bboxCoordinatesPrint'),
                tags$strong('classificationDF'), verbatimTextOutput('classificationDFPrint'),
                tags$strong('segmentationDF'), verbatimTextOutput('segmentationDFPrint')
            )
        )
    )
)
