traceOutput <- function(id) {
    ns <- NS(id)

    tagList(
        a(id=ns("toggleAdvanced"), "Show/hide Advanced Information"),
        #shinyjs::hidden(
            div(id=ns("advanced"),
                wellPanel(
                    # DIAGNOSTIC UI CODE GENERATED BY `cg.R`
                    h2('Inputs'),
                    shiny::tags$strong('radiologist'), verbatimTextOutput(ns('radiologistPrint')),

                    h2('Conductors'),
                    shiny::tags$strong('usrImpressionDf'), verbatimTextOutput(ns('usrImpressionDfPrint')),
                    shiny::tags$strong('SD'), verbatimTextOutput(ns("SDPrint")),
                    shiny::tags$strong('usageLst'), verbatimTextOutput(ns('usageLstPrint'))
    )))#)
}

#! TODO: trace <- function(input, output, session, ...) {}
#        traceOutput <- function(id, ...) {}
trace <- function(input, output, session,
                  radiologistIn, usrImpressionDf,
                  SD, usageLst) {
    # Supplementary Info panel for diagnostics
    shinyjs::onclick("toggleAdvanced",
                     shinyjs::toggle("advanced", anim=TRUE))

    # DIAGNOSTIC SERVER CODE GENERATED BY `cg.R`

    # Reactive Inputs
    output$radiologistPrint <- renderPrint(radiologistIn() %>% str())

    # Reactive Conductors
    output$usrImpressionDfPrint <- renderPrint(usrImpressionDf() %>% str())
    output$SDPrint <- renderPrint(SD() %>% str())
    output$usageLstPrint <- renderPrint(usageLst() %>% str())
}
