traceOutput <- function(id) {
    ns <- NS(id)

    tagList(
        a(id=ns("toggleAdvanced"), "Show/hide Advanced Information"),
        shinyjs::hidden(
            div(id=ns("advanced"),
                wellPanel(
                    h2('Mouse Image Coordinates'),
                    verbatimTextOutput(ns("mouseHoverTable")),

                    # DIAGNOSTIC UI CODE GENERATED BY `cg.R`
                    h2('Inputs'),
                    shiny::tags$strong('radiologist'), verbatimTextOutput(ns('radiologistPrint')),
                    shiny::tags$strong('mainImageId'), verbatimTextOutput(ns('mainImageIdPrint')),

                    h2('Conductors'),
                    shiny::tags$strong('idDf'), verbatimTextOutput(ns('idDfPrint')),
                    shiny::tags$strong('usrInptDf'), verbatimTextOutput(ns('usrInptDfPrint')),
                    shiny::tags$strong('similarImgDf'), verbatimTextOutput(ns('similarImgDfPrint')),
                    shiny::tags$strong('usage_data'), verbatimTextOutput(ns('usage_dataPrint'))
    ))))
}

#! TODO: trace <- function(input, output, session, ...) {}
#        traceOutput <- function(id, ...) {}
trace <- function(input, output, session,
                  radiologistIn, mainImageIdIn, radHover,
                  idDf, usrInptDf, similarImgDf, usage_data) {
    # Supplementary Info panel for diagnostics
    shinyjs::onclick("toggleAdvanced",
                     shinyjs::toggle("advanced", anim=TRUE))

    output$mouseHoverTable <- renderPrint(radHover() %>% str())

    # DIAGNOSTIC SERVER CODE GENERATED BY `cg.R`

    # Reactive Inputs
    output$radiologistPrint <- renderPrint(radiologistIn() %>% str())
    output$mainImageIdPrint <- renderPrint(mainImageIdIn() %>% str())

    # Reactive Conductors
    output$idDfPrint <- renderPrint(idDf() %>% str())
    output$usrInptDfPrint <- renderPrint(usrInptDf() %>% str())
    output$similarImgDfPrint <- renderPrint(similarImgDf() %>% str())
    output$usage_dataPrint <- renderPrint(usage_data() %>% str())
}
