function(input, output, session) {
    # Serve outputs -----------------------
    # Reactive UI elements
    output$imgIdUi <- renderUI({
        selectInput("imgIdIn", "Image:", choices=kAVAIL_TEST_IDS)
    })

    # Clinical Outputs
    ## Radiograph
    output$radiographImage <- renderImage({
        filename <- stringr::str_interp("${kDIR_SMALL_IMGS}/${input$imgIdIn}.jpg")
        return(list(src = filename, filetype="image/jpeg", alt="Radiograph"))
    }, deleteFile = FALSE)

    # Brush Coordinates
    output$coordinatesTable <- renderTable({bboxCoordinates()})

    # Downloads
    output$downloadClassification <- handle_annotation_download("Classification")
    output$downloadSegmentation <- handle_annotation_download("Segmentation")
    output$downloadClinicalNote <- handle_annotation_download("ClinicalNote")

    # Reactive Conductors -----------------
    ids <- reactive({
        id_fields <- c("user_name", "imgIdIn")
        x <- map(id_fields, function(x) x=input[[x]])
        x$timestamp <- Sys.time()
        x %<>% as.data.frame() %>% purrr::set_names(c("Radiologist Name", "Image ID", "Timestamp"))
    })

    bboxCoordinates <- reactive({
        data.frame(input$bbox_brush[c("xmin", "xmax", "ymin", "ymax")]) %||% data.frame()
    })

    classificationDF <- reactive({
        df <- ids()
        df$Pathologies <- toString(input$pathologies)
        df
    })

    segmentationDF <- reactive({
        df <- ids()
        coords <- bboxCoordinates()
        bind_cols(df, coords)
    })

    clinicalNoteDF <- reactive({
        df <- ids()
        df$ClinicalNote <- input$note
        df
    })


    # Reactive Observers -------------------------------------------------------
    # I/O buttons
    observeEvent(
        eventExpr = input$submit_classification,
        label = "submitClassification_obsEvnt",
        handlerExpr = {
          save_annotation(classificationDF(), "Classification")
          log_usr_event(input$user_name, "submit_classification", dir = kDIR_LOG, img_id = input$imgIdIn)
        }
    )

    observeEvent(
        input$submit_cardiomegaly,
        handlerExpr = {
          save_segmentation(segmentationDF(), "cardiomegaly")
          log_usr_event(input$user_name, "submit_segmentation", dir = kDIR_LOG, img_id = input$imgIdIn)
        }
    )
    observeEvent(
        input$submit_emphysema,
        handlerExpr = {
          save_segmentation(segmentationDF(), "emphysema")
          log_usr_event(input$user_name, "submit_segmentation", dir = kDIR_LOG, img_id = input$imgIdIn)
        }
    )
    observeEvent(
        input$submit_effusion,
        handlerExpr = {
          save_segmentation(segmentationDF(), "effusion")
          log_usr_event(input$user_name, "submit_segmentation", dir = kDIR_LOG, img_id = input$imgIdIn)
        }
    )

    observeEvent(
        input$submit_note,
        handlerExpr = {
          save_annotation(clinicalNoteDF(), "ClinicalNote")
          log_usr_event(input$user_name, "submit_note", dir = kDIR_LOG, img_id = input$imgIdIn)
        }
    )

    # Conditionally hide/disable segmentation submission
    observe(shinyjs::toggle("segmentation", anim=TRUE, condition=!is.null(input$pathologies)))
    observe(shinyjs::toggleState("submit_cardiomegaly",
                                 condition = nrow(bboxCoordinates()) > 0 && "cardiomegaly" %in% input$pathologies))
    observe(shinyjs::toggleState("submit_emphysema",
                                 condition = nrow(bboxCoordinates()) > 0 && "emphysema" %in% input$pathologies))
    observe(shinyjs::toggleState("submit_effusion",
                                 condition = nrow(bboxCoordinates()) > 0 && "effusion" %in% input$pathologies))


    # Image/Annotation Sources ---------
    output$imgFp <- renderPrint(kDIR_SMALL_IMGS %>% cat())
    output$annFp <- renderPrint(kDIR_USR_INPT %>% cat())


    # Trace -----------------------------
    # Supplementary Info panel for diagnostics
    shinyjs::onclick("toggleAdvanced",
                     shinyjs::toggle("advanced", anim=TRUE))

    # DIAGNOSTIC SERVER CODE GENERATED BY `cg.R`

    # Reactive Inputs
    output$imgIdInPrint <- renderPrint(input$imgIdIn %>% str())
    output$userNamePrint <- renderPrint(input$user_name %>% str())
    output$pathologiesPrint <- renderPrint(input$pathologies %>% str())
    output$notePrint <- renderPrint(input$note %>% str())

    # Reactive Conductors
    output$idsPrint <- renderPrint(ids() %>% str())
    output$bboxCoordinatesPrint <- renderPrint(bboxCoordinates() %>% str())
    output$classificationDFPrint <- renderPrint(classificationDF() %>% str())
    output$segmentationDFPrint <- renderPrint(segmentationDF() %>% str())
    output$clinicalNoteDFPrint <- renderPrint(clinicalNoteDF() %>% str())
}
