---
output: html_document
---

## Help
CANDI uses various R packages to create an interactive browser-based dashboard (R language; v3.4; 2017-09-28).  The rshiny package provides an R interface into the html and javascript components of a web page.  Specialized packages perform radiograph handling and cloud data storage.  Dashboards discussed in this manuscript were deployed on a Nginx cloud-based server running Ubuntu, which hosts the accompanying webpage: candi.nextgenhealthcare.org.  This web site provides deidentified demos, usage instructions, and the application source code.


## How To Use
CANDI is a flexible framework that can be customized for new input data, annotation types, dashboard contents, or clinical trial randomization routines.

### Input Format
Existing apps ingest jpeg images, but the the `EBImage` package (currently implemented) can open any standard image format.  Specialized medical image formats, such as dicom images, can be incorporated via integrating third-party packages like `oro.dicom`.

### Input Source
We demonstrate three approaches to data input in the CANDI RAD examples, which are suitable for the following use cases:

* Institutional: images and metadata are hosted on the same server that hosts the CANDI application
* Consortia: users can upload images directly from their personal machine via the CANDI app
* Public: images are fetched from the NIH funded [OpenI database](https://openi.nlm.nih.gov/) on demand

### Input Sources
The public apps hosted on this site contain public images from 2 sources that have been manually reviewed to confirm de-identification.

* [IU](
https://openi.nlm.nih.gov/services.php?it=xg
): 7,399* AP, PA, and Lateral radiographs
* [NIH](https://nihcc.app.box.com/v/ChestXray-NIHCC): 48,902 AP and PA radiographs

* meeting inclusion critera (see associated manuscript for details)

### User Interface:
The user interface is specified by the ui.R script.

## DL Toolkit
We trained Convolutional Neural Networks (CNN) on each of the annotation types in CANDI RAD to generate supervised classification, segmentation, and image captioning models.  We also used a CNN in an unsupervised fashion to implement an similar search.

