---
output: html_document
---

# Visualization

There are 2 CANDI implementations to address bottlenecks to translating deep learning to medical radiology:

1. Radiograph Annotation Dashboard (RAD)
2. Computer-Aided Diagnosis (CAD) Evaluation

## Radiogrpah Annotation Dashboard (RAD)
Use the following image-only apps to collect training data for classification, segmentation, and imaging captioning models. Apps have different image/annotation I/O depending on the use case.

* [institutional annotation app](https://candi.nextgenhealthcare.org/CANDI_RAD_institution/): Institutional servers can display locally stored images and save annotations locally. Use this on a secure server for proprietary/sensitive data.

* [consortia annotation app](https://candi.nextgenhealthcare.org/CANDI_RAD_consortia/): A shared consortia server can have users from different sites upload images temporarily to provide annotations.

* [public annotation app](https://candi.nextgenhealthcare.org/CANDI_RAD_public/): Publically available data can be directly fetched from APIs, and users can provide annotations to a shared google sheet for the communities benefit.

Alternatively use a multimodal databoard to provide users with a more clinical relevant collection of information to inform their interpretations.

* [Multimodal Annotation Dashboard](https://candi.nextgenhealthcare.org/resident/): While the classic computer vision task may be interpreting an isolated image, radiologists consider other aspects of a patient when interpreting radiographic studies.  This dashboard provides users with all the demographic and note data availability in the OpenI database.


## Computer-Aided Diagnosis Evaluation
Once you have a trained image model, use CANDI CAD to flexibly provide assistance to users while/after they interpret an image to assess whether the CAD tool improves interpretation accuracy and/or speed.

* [Deep Learning CAD Toolkit](https://candi.nextgenhealthcare.org/CANDI_CAD/)

* [CAD Randomized Controlled Trial](https://candi.nextgenhealthcare.org/student/)