function(input, output, session) {
    # Reactive elements bound to lower camel case names

    # Invoke modules ----------------------
    usrInptDf <- callModule(impression, "impression")
    similarImgDf <- callModule(similarImg, "similarImg",
                               testImgId = reactive(input$mainImageId),
                               test_pc_df = test_pc_df,
                               hist_imgs_df = hist_imgs_df,
                               hist_img_dir=kHIST_IMG_IN_DIR,
                               dx_chr=kDXS_CHR)

    # Reactive Conductors -----------------
    idDf <- reactive({
        x <- map(kID_FIELDS, function(x) x=input[[x]])  # collect form id fields
        x %<>% as.data.frame() %>% purrr::set_names(c(kID_FIELDS))
        #!TODO: add session id to ids
    })

    # Compute similarities of historical images for the current test image
    testImgPcDf <- reactive({test_pc_df %>%
        filter(img_id == input$mainImageId) %>%
        select(starts_with("PC"))
    })


    cdata <- session$clientData
    usage_data <- reactive({
        cnames <- names(cdata)
        cvals <- lapply(cnames, function(name) {cdata[[name]]})
        cvals %>% set_names(cnames)
    })

    # Serve outputs ------------------------------------------------------------
    # Test Radiograph
    output$mainImage <- renderImage({
        filename <- stringr::str_interp("${kTEST_IMG_IN_DIR}/${input$mainImageId}.jpg")
        return(list(src = filename, filetype="image/jpeg", alt="Main Radiograph"))
    }, deleteFile = FALSE)

    # CNN Test Image Predictions
    output$cnnPyTbl <- renderTable({
        test_py_df %>%
            filter(img_id == input$mainImageId) %>%
            select(-img_id) %>%
            gather(key=diagnosis, value=probability) %>%
            arrange(desc(probability))
    })




    # Reactive Event Handlers --------------------------------------------------
    observeEvent(input$submit_impression, {
        usr_input <- bind_cols(idDf(), usrInptDf()) %>%
            add_column(timestamp = date_time_stamp(), .before=1)
        log <- bind_cols(idDf(), usage_data()) %>%
            add_column(timestamp = date_time_stamp(), .before=1)
        save_usr_input(usr_input)
        save_usr_usage(log)
    })

    # UI toggle panel events
    shinyjs::onclick("toggleCnnPy",
        shinyjs::toggle("cnnPyUi", anim=TRUE))

    # Trace ---------------------------------
    # Supplementary Info panel for diagnostics
    shinyjs::onclick("toggleAdvanced",
                     shinyjs::toggle("advanced"))

    output$mouseHoverTable <- renderPrint(input$radHover %>% str())
    # Values from cdata returned as text
    output$clientdataText <- renderText({
        cnames <- names(cdata)
        allvalues <- lapply(cnames, function(name) {
            paste(name, cdata[[name]], sep = " = ")
        })
        paste(allvalues, collapse = "\n")
    })

    # DIAGNOSTIC SERVER CODE GENERATED BY `cg.R`

    # Reactive Inputs
    output$colorInPrint <- renderPrint(input$colorIn %>% str())
    output$facetRowInPrint <- renderPrint(input$facetRowIn %>% str())
    output$facetColInPrint <- renderPrint(input$facetColIn %>% str())
    output$radiologistPrint <- renderPrint(input$radiologist %>% str())
    output$mainImageIdPrint <- renderPrint(input$mainImageId %>% str())
    output$dxChkbxInPrint <- renderPrint(input$dxChkbxIn %>% str())
    output$noteTxtInPrint <- renderPrint(input$noteTxtIn %>% str())
    output$xPrint <- renderPrint(input$x %>% str())
    output$yPrint <- renderPrint(input$y %>% str())

    # Reactive Conductors
    output$idDfPrint <- renderPrint(idDf() %>% str())
    output$usrInptDfPrint <- renderPrint(usrInptDf() %>% str())
    output$testImgPcDfPrint <- renderPrint(testImgPcDf() %>% str())
    output$similarImgsDfPrint <- renderPrint(similarImgDf() %>% str())
    output$usage_dataPrint <- renderPrint(usage_data() %>% str())
}

