fluidPage(
    shinyjs::useShinyjs(),
    theme = shinytheme("darkly"),
    div(id="title", align="center",
        titlePanel("CANDI for Computer Assisted Diagnosis", windowTitle="CANDI CAD")),

    # Main image row: 3 columns [img/id, radiologist impression, cnn prediction]
    fluidRow(
        # Main ID/Image panel
        column(4,
            fluidRow(
                column(6,
                    textInput("radiologist", "Radiologist Name:", value = "Marcus")),
                column(6,
                    selectInput("mainImageId", "Image:", choices=stem(test_img_fns)))
            ),
            hr(),
            # Radiograph --------------
            div(id="mainImageUi", align="center",
                imageOutput("mainImage", width = 299, height=299,
                    hover = hoverOpts(id = "radHover", delayType = "throttle")))
        ),
        # Current Radiologist Impression ----------
        column(4,
            h3("Your Impression"),
            p(strong("Is there radiographic evidence for a diagnosis?")),
            checkboxGroupInput("dxChkbxIn", label=NULL, choices=kDXS_CHR),
            hr(),
            p(strong("Clinical Note:")),
            textAreaInput("noteTxtIn", NULL, "Clinical Impression", resize = "both"),
            actionButton("submit_impression", "Submit Impression")
        ),
        # ConvNet Assistance --------------
        column(4,
	        a(id="toggleCnnPy", "Show/hide CNN Prediction"),
	        #shinyjs::hidden(
	        div(id="cnnPyUi", wellPanel(
                h3('CNN Prediction'),
	            tableOutput("cnnPyTbl")
    )))),  # end main fluidrow
    hr(),

    # Optional Similar Image Browser Utility -----------------------------------
    a(id="toggleBrowseSimilar", "Show/hide Similar Image Records"),
    #shinyjs::hidden(div(id="browseSimilarUi",
    div(id="browseSimilarUi",
        fluidRow(
            # User Input Panel -------------------
            column(4,
                   wellPanel(
                       selectInput("x", label="x variable:", choices=str_c("PC", 1:10), selected="PC1"),
                       selectInput("y", label="y variable:", choices=str_c("PC", 1:10), selected="PC2"),
                       uiOutput("colorUi"),
                       uiOutput("facetRowUi"),
                       uiOutput("facetColUi")
            )),
            # PC scatter -------------------------
            column(4,
                   plotOutput('pcaPlot', width="100%", click="plot_click",
                              hover = hoverOpts(id="plot_hover", delayType="throttle"),
                              brush = brushOpts(id="plot_brush"))
            ),
            # Historical Documentation Panel -----------------
            column(4,
                   h3("Historical Documentation:"),
                   div(id="similarImageUi", align="center",
                       imageOutput("hoverImage", width = 299, height=299)),
                   tableOutput("hoverYTbl"),  # Diagnosis Tbl
                   textOutput("hoverNoteText")  # Free Text Note
        )),
        fluidRow(
            dataTableOutput("brushedPointsTable")
        )
    ), #),  # END `browseSimilarUi` div
    hr(),

    a(id="toggleAdvanced", "Show/hide Advanced Information"),
    shinyjs::hidden(
        div(id="advanced",
            wellPanel(
                h2('Mouse Image Coordinates'),
                verbatimTextOutput("mouseHoverTable"),
                h2('Session Usage Data'),
                verbatimTextOutput("clientdataText"),

                # DIAGNOSTIC UI CODE GENERATED BY `cg.R`

                h2('Inputs'),
                shiny::tags$strong('colorIn'), verbatimTextOutput('colorInPrint'),
                shiny::tags$strong('facetRowIn'), verbatimTextOutput('facetRowInPrint'),
                shiny::tags$strong('facetColIn'), verbatimTextOutput('facetColInPrint'),
                shiny::tags$strong('radiologist'), verbatimTextOutput('radiologistPrint'),
                shiny::tags$strong('mainImageId'), verbatimTextOutput('mainImageIdPrint'),
                shiny::tags$strong('dxChkbxIn'), verbatimTextOutput('dxChkbxInPrint'),
                shiny::tags$strong('noteTxtIn'), verbatimTextOutput('noteTxtInPrint'),
                shiny::tags$strong('x'), verbatimTextOutput('xPrint'),
                shiny::tags$strong('y'), verbatimTextOutput('yPrint'),

                h2('Conductors'),
                shiny::tags$strong('idDf'), verbatimTextOutput('idDfPrint'),
                shiny::tags$strong('usrInptDf'), verbatimTextOutput('usrInptDfPrint'),
                shiny::tags$strong('testImgPcDf'), verbatimTextOutput('testImgPcDfPrint'),
                shiny::tags$strong('similarImgsDf'), verbatimTextOutput('similarImgsDfPrint'),
                shiny::tags$strong('usage_data'), verbatimTextOutput('usage_dataPrint'),
                shiny::tags$strong('pcaPlot'), verbatimTextOutput('pcaPlotPrint'),
                shiny::tags$strong('hoverImgId'), verbatimTextOutput('hoverImgIdPrint')
))))
