fluidPage(
    shinyjs::useShinyjs(),
    theme = shinythemes::shinytheme("darkly"),
    div(id="title", align="center",
        titlePanel("CANDI Public Radiograph Annotation Dashboard", windowTitle="CANDI RAD")),

    sidebarLayout(
        sidebarPanel(
            textInput("user_name", "User Name:", value = "Marcus"),
            selectInput("img_id", "Fetch image from OpenI", choices=names(iu_db_lut)),
            hr(),

            p("Data Locations:"),
            a(href="https://openi.nlm.nih.gov", p("Image loaded from OpenI"),
              verbatimTextOutput("radiographURL")),
            a(href=gsURL, p("Annotations stored on Google Drive"),
              verbatimTextOutput("annotationURL")),
            hr(),

            p("Downloads:"),
            div(align="center",
                downloadButton("downloadClassification", label="Classification Annotations"),
                downloadButton("downloadSegmentation", label="Segmentation Annotations"),
                downloadButton("downloadClinicalNote", label="Clinical Impression Notes")
            )
        ),

        mainPanel(
            # Display Radiograph ---------------
            fluidRow(
                column(4, offset=3,
                    div(id="image", align="center",
                        imageOutput("radiographImage", width = 299, height = 299,
                                    brush = brushOpts(id = "bbox_brush", resetOnNew = TRUE))
            ))),

            # Classification ----------
            fluidRow(
                column(width = 8,
                       checkboxGroupInput("pathologies", "What pathologies are present in the image?",
                                          choices=indications)
                ),
                column(width = 4,
                       shiny::tags$br(),
                       actionButton("submit_classification", "Submit Classifications"))
            ),

            # Segmentation -------------
            div(id="segmentation",
                p(strong("Draw a box around the evidence for each identified pathology (submit 1 box per pathology).")),
                fluidRow(
                    div(id="seq_in_panel", align="center",
                        column(width = 5,
                               fluidRow(actionButton("submit_cardiomegaly", "Submit Cardiomegaly Segmentation")),
                               fluidRow(actionButton("submit_emphysema", "Submit Emphysema Segmentation")),
                               fluidRow(actionButton("submit_effusion", "Submit Effusion Segmentation"))
                        ),
                        column(width = 4, shiny::tags$br(), tableOutput("coordinatesTable"))
            ))),

            # Note --------------------
            p(strong("Note Impression:")),
            textAreaInput("note", NULL, "Clinical Impression", width="650px"),
            actionButton("submit_note", "Submit Impression")
    )),
    hr(),

    a(id="toggleAdvanced", "Show/hide Advanced Information"),
    shinyjs::hidden(
        div(id="advanced",
            wellPanel(
                # DIAGNOSTIC UI CODE GENERATED BY `cg.R`
                
                h2('Inputs'),
                shiny::tags$strong('user_name'), verbatimTextOutput('user_namePrint'),
                shiny::tags$strong('img_id'), verbatimTextOutput('img_idPrint'),
                shiny::tags$strong('pathologies'), verbatimTextOutput('pathologiesPrint'),
                shiny::tags$strong('note'), verbatimTextOutput('notePrint'),
                
                h2('Conductors'),
                shiny::tags$strong('ids'), verbatimTextOutput('idsPrint'),
                shiny::tags$strong('bboxCoordinates'), verbatimTextOutput('bboxCoordinatesPrint'),
                shiny::tags$strong('classificationDF'), verbatimTextOutput('classificationDFPrint'),
                shiny::tags$strong('segmentationDF'), verbatimTextOutput('segmentationDFPrint'),
                shiny::tags$strong('clinicalNoteDF'), verbatimTextOutput('clinicalNoteDFPrint')
            )
        )
    )
)
