# Metaprogram over the shiny app to generate code for a status board of reactive
# source and conductors.
# Run from the application directory

options(stringsAsFactors = FALSE)

# Metaprogramming input --------------------------------------------------------
# Identify reactive inputs and expressions from application source code files

# Reactive Variable identifier (+/- type) regex parse pattern
(regex_inpt_type_id <- capture(one_or_more(ALPHA)) %R%
     "Input" %R% OPEN_PAREN %R% rebus::or("'", '"') %R%
     capture(one_or_more(WRD)) %R% rebus::or("'", '"'))
(regex_cond_id <- capture(one_or_more(rebus::or(WRD, DOLLAR))) %R%
        optional(SPC) %R% "<-" %R% optional(SPC) %R%
        "reactive" %R% OPEN_PAREN)

# Code/String manipulation fxns
.grepR <- function(pattern) {
    # Execute a grep statement on the terminal to search app R scripts for `pattern`
    #
    # Args
    #   pattern character(1) pattern to match
    # Value
    #   character vector, each element is one file line that contains `pattern`
    # Side Effect
    #   prints an HTML viewer of line matches in the Viewer panel
    cmd <- str_interp('grep -rn --include="*.R" ${pattern} server.R ui.R global.R',
                      env = list(pattern=pattern))
    hits <- system(cmd, intern=TRUE)
    str_view(hits, pattern) %>% print
    hits
}

meta_rxtive_var_match <- function(coarse_fixed_pat, fine_regex_pat) {
    hits <- .grepR(pattern=coarse_fixed_pat)
    str_view(hits, fine_regex_pat) %>% print
    input_types_ids <- hits %>%
        str_subset(fine_regex_pat) %>%
        str_match(fine_regex_pat)
}

# Reactive variable extraction
rxtive_inpts <- meta_rxtive_var_match("Input", regex_inpt_type_id) %>%
    `[`(, 2:3) %>%
    as.data.frame() %>%
    tibble::deframe()

rxtive_exprs <- meta_rxtive_var_match("reactive", regex_cond_id) %>%
    `[`(, 2)


# Code Generation output -------------------------------------------------------
# Code line string templates
server_inpt_template <- "output$${var}Print <- renderPrint(input$${var} %>% str())"
server_expr_template <- "output$${var}Print <- renderPrint(${var}() %>% str())"

ui_inpt_template <- "shiny::tags$strong('${var}'), verbatimTextOutput('${var}Print'),"
ui_expr_template <- "shiny::tags$strong('${var}'), verbatimTextOutput('${var}Print'),"

# Code/string manipulation functions
embed_code <- function(x, template) {
    map_chr(x,
            ~ str_interp(template, env = list(var = .x)))
}

generate_diagnostic_code <- function(app_file, inpt_template, expr_template, section_f,
                                     inpts = rxtive_inpts, exprs = rxtive_exprs) {
    # Generate code for either the server or ui application files
    list(
        str_c("# DIAGNOSTIC ", str_to_upper(app_file), " CODE GENERATED BY `cg.R`"),
        section_f('Inputs'),
        embed_code(inpts, inpt_template),
        section_f('Conductors'),
        embed_code(exprs, expr_template)
    ) %>% walk(cat, sep="\n")
}


# Code Generation
generate_diagnostic_code("server", server_inpt_template, server_expr_template,
                         section_f = function(x) str_interp("\n# Reactive ${x}"))
generate_diagnostic_code("ui", ui_inpt_template, ui_expr_template,
                         section_f = function(x) str_interp("\nh2('${x}'),"))
