function(input, output, session) {
    # Serve outputs -----------------------
    output$radiographImage <- renderImage({
        # Fetch the requested image, save to temp file, push to client, delete temp file
        img_url <- iu_db_lut[input$img_id]
        img <- EBImage::readImage(img_url) %>%
            EBImage::resize(w=299,h=299)
        temp_fp <- tempfile(fileext = ".jpg")
        EBImage::writeImage(img, temp_fp)

        list(src = temp_fp, filetype="image/jpeg")
    }, deleteFile = TRUE)

    # Brush Coordinates
    output$coordinatesTable <- renderTable({bboxCoordinates()})

    # Downloads
    output$downloadClassification <- handle_annotation_download("Classification")
    output$downloadSegmentation <- handle_annotation_download("Segmentation")
    output$downloadClinicalNote <- handle_annotation_download("ClinicalNote")

    # Image/Annotation Sources
    output$radiographURL <- renderText(iu_db_lut[input$img_id])
    output$annotationURL <- renderText(gsURL)

    # Reactive Conductors -----------------
    ids <- reactive({
        x <- map(id_fields, function(x) x=input[[x]])
        x$timestamp <- Sys.time()
        x %<>% as.data.frame() %>% set_names(c("User Name", "Image ID", "Timestamp"))
    })

    bboxCoordinates <- reactive({
        data.frame(input$bbox_brush[c("xmin", "xmax", "ymin", "ymax")]) %||% data.frame()
    })

    classificationDF <- reactive({
        df <- ids()
        df$Pathologies <- toString(input$pathologies)
        df
    })

    segmentationDF <- reactive({
        df <- ids()
        coords <- bboxCoordinates()
        bind_cols(df, coords)
    })

    clinicalNoteDF <- reactive({
        df <- ids()
        df$ClinicalNote <- input$note
        df
    })


    # Reactive Observers -------------------------------------------------------
    # I/O buttons
    observeEvent(input$submit_classification,
                 save_annotation(classificationDF(), "Classification"))

    save_segmentation <- function(path) {
        stopifnot(path %in% kDXS_CHR)
        df <- segmentationDF() %>%
            add_column(Pathology=path)
        save_annotation(df, "Segmentation")
    }
    observeEvent(input$submit_cardiomegaly, save_segmentation("cardiomegaly"))
    observeEvent(input$submit_emphysema, save_segmentation("emphysema"))
    observeEvent(input$submit_effusion, save_segmentation("effusion"))

    observeEvent(input$submit_note,
                 save_annotation(clinicalNoteDF(), "ClinicalNote"))

    # Conditionally hide/disable segmentation submission
    observe(shinyjs::toggle("segmentation", anim=TRUE, condition=!is.null(input$pathologies)))
    observe(shinyjs::toggleState("submit_cardiomegaly",
                                 condition = nrow(bboxCoordinates()) > 0 && "cardiomegaly" %in% input$pathologies))
    observe(shinyjs::toggleState("submit_emphysema",
                                 condition = nrow(bboxCoordinates()) > 0 && "emphysema" %in% input$pathologies)    )
    observe(shinyjs::toggleState("submit_effusion",
                                 condition = nrow(bboxCoordinates()) > 0 && "effusion" %in% input$pathologies))


    # Supplementary Info panel for diagnostics
    shinyjs::onclick("toggleAdvanced",
                     shinyjs::toggle("advanced"))

    # DIAGNOSTIC SERVER CODE GENERATED BY `cg.R`
    
    # Reactive Inputs
    output$user_namePrint <- renderPrint(input$user_name %>% str())
    output$img_idPrint <- renderPrint(input$img_id %>% str())
    output$pathologiesPrint <- renderPrint(input$pathologies %>% str())
    output$notePrint <- renderPrint(input$note %>% str())
    
    # Reactive Conductors
    output$idsPrint <- renderPrint(ids() %>% str())
    output$bboxCoordinatesPrint <- renderPrint(bboxCoordinates() %>% str())
    output$classificationDFPrint <- renderPrint(classificationDF() %>% str())
    output$segmentationDFPrint <- renderPrint(segmentationDF() %>% str())
    output$clinicalNoteDFPrint <- renderPrint(clinicalNoteDF() %>% str())
}
