#' Trace verbatim outputs of reactive variables
#'
#' @export
#' @examples
#' if (interactive()) {
#' library(shiny)
#'
#' shinyApp(
#'     ui = fluidPage(
#'         textInput("user_name", "Radiologist Name:", value = "Marcus"),
#'         traceOutput("trace")
#'     ),
#'     server = function(input, output, session) {
#'         callModule(trace, "trace",
#'                    user_nameIn = reactive(input$user_name),
#'                    usrImpressionDf = reactive(mtcars),
#'                    usageLst = reactive({
#'                        cdata <- session$clientData
#'                        cnames <- names(cdata)
#'                        cvals <- lapply(cnames, function(name) {cdata[[name]]})
#'                        cvals %>% purrr::set_names(cnames)
#'                    }))
#'     }
#' )}
traceOutput <- function(id) {
    ns <- NS(id)

    tagList(
        a(id=ns("toggleAdvanced"), "Show/hide Advanced Information"),
        div(id=ns("advanced"),
            wellPanel(
                # DIAGNOSTIC UI CODE GENERATED BY `cg.R`
                h2('Inputs'),
                shiny::tags$strong('user_name'), verbatimTextOutput(ns('user_namePrint')),

                h2('Conductors'),
                shiny::tags$strong('usrImpressionDf'), verbatimTextOutput(ns('usrImpressionDfPrint')),
                shiny::tags$strong('usageLst'), verbatimTextOutput(ns('usageLstPrint'))
    )))
}

#! TODO: trace <- function(input, output, session, ...) {}
#        traceOutput <- function(id, ...) {}
#' @export
trace <- function(input, output, session,
                  user_nameIn, usrImpressionDf,
                  usageLst) {
    # Supplementary Info panel for diagnostics
    shinyjs::onclick("toggleAdvanced",
                     shinyjs::toggle("advanced", anim=TRUE))

    # DIAGNOSTIC SERVER CODE GENERATED BY `cg.R`
    # Reactive Inputs
    output$user_namePrint <- renderPrint(user_nameIn() %>% str())

    # Reactive Conductors
    output$usrImpressionDfPrint <- renderPrint(usrImpressionDf() %>% str())
    output$usageLstPrint <- renderPrint(usageLst() %>% str())
}
